<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-CarRental.Kafka-c2066e95-233a-4cc9-90d3-d7fb5a311e70</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" Version="35.6.5" />
		<PackageReference Include="Confluent.Kafka" Version="2.12.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CarRental.Application.Contracts\CarRental.Application.Contracts.csproj" />
		<ProjectReference Include="..\CarRental.ServiceDefaults\CarRental.ServiceDefaults.csproj" />
	</ItemGroup>
</Project>